### PR TITLE
fix skipping linting of last repo

### PR DESCRIPTION
**Pull request by bernt-matthias**
due to missing newline at the end of the repo list file
the while loop skips the last lint.

also extended the test

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Do you think we should document `lint_report.txt`?

**Comment by mvdbeek** [comment]
> Do you think we should document `lint_report.txt`?

I'd consider this a test output for the action, I don't think this is useful for deployers ?

**Comment by bernt-matthias** [comment]
> I'd consider this a test output for the action, I don't think this is useful for deployers ?

I thought about putting the output of all three linters in the IUC workflow to artifacts. Then tool developers have all relevant output in artifacts.

**Comment by mvdbeek** [comment]
Ok, then we should indeed document it :)

**Comment by bernt-matthias** [comment]
OK. Ready to go.

**Comment by bernt-matthias** [comment]
I will create a new release.

**Pull request merged**
